### ISSUE TITLE
mint can overflow totalSupply, giving false impression of scarcity

### ISSUE THREAD

**Issue by epheph** [ProjectOpenSea/opensea-erc1155#11]
https://github.com/ProjectOpenSea/opensea-erc1155/blob/59d2e0cd3b118d8aeb0ac27c4b0726feff3853c0/contracts/ERC1155Tradable.sol#L125-L133

Address-A receives a mint of 2, totalSupply: 2
Address-B receives a mint of 2^256-1, totalSupply: 1

**Comment by Cybourgeoisie** [comment]
Not an issue due to the SafeMath checks within both mint and batchMint.

**Comment by stuckinaboot** [comment]
This issue should be closed right?

**Comment by epheph** [comment]
Looks fixed in #15
