### ISSUE TITLE
Value Precision

### ISSUE THREAD

**Issue by emtesenair** [ProjectOpenSea/opensea-erc1155#20]
What is the value precision OpenSea uses for 1155?

**Comment by alexanderatallah** [comment]
Hi! What do you mean by "value precision"?
We use SafeMath and don't convert units of payment inside the smart contract.

**Comment by emtesenair** [comment]
How are decimals represented within a class, if at all?

Should 1 = 1 or 1 = 1000000000000000000 wei

**Comment by alexanderatallah** [comment]
When interacting with smart contracts, like in this repo, 1=1 (1 wei). When interacting with "amounts" in the javascript SDK, you pass in the unit amount, so divided by 10^18 for ETH. See https://github.com/ProjectOpenSea/opensea-js#making-offers
