### ISSUE TITLE
Can't not mint again!

### ISSUE THREAD

**Issue by jhbum001** [ProjectOpenSea/opensea-erc1155#40]
With opensea creatures, I deployed it on the rinkeby network, and I succeeded in minting with erc1155.
After minting, 3 OpenSeaCreatureItem sales were created. 
After 4 days, I tried min again, but the operation ended without an error or success message. Can't I mint again after minting once?

**Comment by chahakshah111** [comment]
try:- truffle migrate --reset
if that does not work try:- truffle depoly and then truffle migrate --reset
